pipeline {
    agent any


    environment {
        CI = 'true'
        CLIENT_ID=0oams1il08SC8D5UX5d5
        ISSUER=https://dev-9213540.okta.com/oauth2/default
    }
    stages {
        stage('Build') {
            steps {
                
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Starting Delivery to local Docker.."'
                sh './jenkins/scripts/deliver.sh'

                sh 'echo "Delivery Complete."; exit 0'
            }
        }
    }
}
