pipeline {
    agent any
    triggers {
        pollSCM()
    }

    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "delivery will take place here.."'
                //sh './jenkins/scripts/deliver.sh'
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
                //sh './jenkins/scripts/kill.sh'
                sh 'echo "No delivery required"; exit 0'
            }
        }
    }
}
